name: Nameservers

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  check-dns:
    runs-on: self-hosted
    container:
      image: cunnie/fedora-golang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DNS check
        run: ginkgo -r -p spec/
        env:
          DOMAINS: nip.io,sslip.io # You can set your domain here if needed
